### ISSUE TITLE
zip committed in git

### ISSUE THREAD

**Issue by bhaible** [cppp-project/cppp-reiconv#1]
`tests/standard.zip` was committed in git. This is not a good practice, because
- when the developer modifies one of the files in it, they need to re-pack the zip.
- git cannot show the history of the individual files in the zip,
- when committing a modified zip several times, the total size of the .git directory will grow quickly.

**Comment by bhaible** [comment]
The recommended practice is to create a directory and commit individual files.

**Comment by ChenPi11** [comment]
Thank you. In the new version (origin/dev), we have removed the old version of tests and used libiconv/tests/ as the test suite instead. :)

https://github.com/cppp-project/cppp-reiconv/commit/7ce3aba16292069f9fc6a8bf38f5e236173bc002
